[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_GEMINI_KEY = "AIzaSyC8t4BbhGNJRO96QHVRVaYJdvDKLzlpPxo"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
